# Agenda

última versión: `r lubridate::now()`


| Lunes 13               |                                                                 |
|:------------------ |:-------------------------------------------------------------------------- |
9:30am              | Transporte busca a los participantes en el Hotel para llevarlos al INVEMAR
10:00am - 11:30am   | Bienvenida al INVEMAR *Paula Sierra*. Introducción al Taller. Presentación de los participantes. <br> Programas globales de monitoreo de la biodiversidad. MBON. Programa de Monitoreo de la biodiversidad marina Polo a Polo de las Américas. *Enrique Montes*. <br>
11:30am - 12:00m    | Recorrido por las instalaciones del INVEMAR
12:00m - 1:00pm     | Almuerzo en el INVEMAR
1:00pm - 3:15pm     | Introducción a los sistemas de Pastos Marinos. *Diana Gómez*. <br> Método de estimación de cobertura y biomasa en pastos marinos. *Diana Gómez*.  <br> Los peces asociados a los pastos marinos *Juan David Gonzalez*.  <br>
3:15pm - 3:30pm     | Receso café
3:30pm - 5:00pm     | Método de medición de la tasa depredación de peces (SquidPops). Ensamblaje de los SquidPops. *Jonathan Leafcheck*.



| Martes 14           |                                                               |
|:------------------ |:-------------------------------------------------------------------------- |
8:00am              | Transporte del hotel al INVEMAR
8:30am - 4:00pm     | Trabajo de Campo. PN Tayrona. Instalación de los SquidPops. Estimación de la cobertura y extracción de muestras para biomasa de *Thalassia*.
4:00pm - 5:00pm     | Procesamiento de muestras |


| Miércoles 15           |                                                               |
|:------------------ |:-------------------------------------------------------------------------- |
8:00am              | Transporte del hotel al INVEMAR
8:30am - 12:00m     | Trabajo de Campo. PN Tayrona. <br> Procesamiento de muestras en INVEMAR.
12:00m - 1:00pm     | Almuerzo
1:00pm - 3:15pm     | Los pastos marinos dentro del marco del programa de Observación Global del Océano GOOS biology & Ecosystems *Patricia Miloslavich*. <br> Procesamiento de muestras/vídeos
3:15pm - 3:30pm     | Receso café
3:30pm - 4:15pm     | Sistema de Información Biogeográfica del Océano OBIS *Eduardo Klein*.
4:15pm - 5:00pm     | Procesamiento de muestras



| Jueves 16              |                                                              |
|:------------------ |:-------------------------------------------------------------------------- |
8:00am              | Transporte del hotel al INVEMAR
8:30am - 10:15am    | Herramientas satelitales para le estudio del océano. Ejercicios de extracicón de TSM y Chl. *Enrique Montes*.
10:15am - 10:30am   | Receso café
10:30am - 12:00m    | Análisis de datos. Protocolos. *Jonathan Lefcheck, Eduardo Klein* 
12:00m - 1:00pm     | Almuerzo INVEMAR
1:00pm - 3:15pm     | Análisis de datos
3:15pm - 3:30pm     | Receso café
3:30pm - 5:00pm     | Análisis de datos


| Viernes 17             |                                                              |
|:------------------ |:-------------------------------------------------------------------------- |
8:00am              | Transporte del hotel al INVEMAR
8:30am - 10:15am    | Procesamineto de datos. Elaboración de los metadatos. Carga de datos en el IPT del nodo regional OBIS del Caribe.
10:15am - 10:30am   | Receso café
10:30am - 12:00m    | Presentación de resultados por grupo. Cierre del Taller
12:00m - 1:00pm     | Almuerzo INVEMAR

