# Logística

El taller se realizará en las instalaciones del INVEMAR, Santa Marta. Colombia. Los trabajos de campo se realizarán en la Bahía de Chengue, PN Tayrona. 

```{r map, echo=FALSE}
library(leaflet)


m = leaflet() %>% addTiles() %>% addMarkers(lat = c(11.18855, 11.321587), 
                                            lng=c(-74.23079, -74.131489), 
                                            label = c("INVEMAR", "Bahía Chengue")) %>% 
  addMiniMap()

m

```



## Antes del Taller

1. Todos los participantes deben estar registrados en [OceanExpert](https://www.oceanexpert.net), si aún no lo han hecho
2. Todos los participantes deben tener una cuenta en [Ocean Teacher Global Academy](https://classroom.oceanteacher.org). Si aún no la tienen, por favor regístrense lo antes posible ya que se requiere de confirmación manual y puede tomar hasta dos días en recibirla.
3. **Si estás registrado para bucear debes traer tu cartet de buceo y haber completado la planilla de seguridad que fue enviada por correo**
4. Debes traer al menos tu equipo básico de buceo. El resto será suministrado por el INVEMAR



## En Santa Marta

El domingo 12 de mayo estará un conductor con el uniforme institucional y una tablilla que dice INVEMAR, los estará esperando a la salida del aeropuerto.  Como Enrique es el primero que llega, a esa hora lo estarán recogiendo en el aeropuerto y lo llevaran al hotel.  Stephanía es la segunda que llega pero como su vuelo es tan cercano al de las 22:30, tendrá que esperarlos 45 minutos mientras llega el vuelo de Bogotá y así el transporte los llevará al hotel.  Una logística similar se realizará para sus vuelos de regreso:  el 17 de mayo para Aldo y el 18 de mayo para el resto de los participantes de acuerdo con las horas de sus vuelos.


Durante la semana del 13 al 17 en la mañana y en la tarde, un transporte del INVEMAR los estará recogiendo para traerlos al instituto (ver los horarios de la agenda y será mínimo media hora antes de que comience el evento diariamente) y así mismo será en horas de la tarde hacia el hotel.  Si durante el día se requiere que se movilicen hacia el Rodadero o Santa Marta para asuntos diferentes al del taller, sólo con la autorización de Patricia se solicitará apoyo del transporte del INVEMAR, de otra manera, deberán tomar un taxi el cual se pide en la portería del INVEMAR.   Los almuerzos serán tomados en el Instituto todos los días, exceptuando el día de la salida de campo en el cual, se llevaran refrigerios y agua suficiente para la jornada y tendrán acceso a su almuerzo en el hotel donde se hospedarán.


Las temperaturas en este momento están entre 33 y 39 grados centígrados con sensación térmica entre 37 y 40 grados.  No ha llovido hasta el momento pero puede que durante la semana de trabajo, suceda.   El peso colombiano es la moneda nacional y talvez sólo en el aeropuerto recibirían dólares en forma de pago, por lo que si pueden hacer el cambio en el aeropuerto en Bogotá sería muy útil aunque sé que en el Rodadero hay un lugar para el cambio de divisas, por si se requiere.


Como dentro de la logística del taller habrá trabajo en el laboratorio biológico y en algún momento al laboratorio de calidad ambiental el 15 de mayo, se aconseja no entrar en sandalias (preferiblemente zapatos cerrados) ni pantalones corticos por seguridad.


El horario laboral del Instituto inicia desde las 7:00 am hasta las 11:30 am en la mañana y en la tarde de las 13 a las 17 horas. 


Las recomendaciones generales en la calle, durante la noche es que carguen con ustedes lo mínimo, si traen cámaras, computadoras, tablets o celulares preferiblemente manténgalos dentro de los bolsos o morrales o en su defecto no los descuiden.  Si van a la playa, entre menos cosas lleven mejor.

El hotel donde llegaran está ubicado en pleno centro del área turística de El Rodadero, y a una cuadra de la playa luego tienen prácticamente muchos sitios comerciales que conocer o visitar durante su estadía en las tardes.  Los horarios para estar dentro del mar estan restringidos en horas de la noche, por favor seguir las indicaciones de las autoridades al respecto.




## Organización del trabajo

Los participantes estarán trabajando en equipos durante toda la semana. Se espera que para el día viernes cada uno de los equipos de trabajo presente el resultado de sus análisis y que cargue los registros de biodiversidad a la base de datos OBIS.

Se espera que los participantes traigan su computador personal para realizar los trabajos durante la semana. Deben tener instalado el [R Studio](https://www.rstudio.com), ya que los análisis se realizarán principalmente en R. 


## Trabajo de Campo/Buceo

El taller incluye un día de trabajo de campo (martes) en la Bahía de Chengue, en el Parque Nacional Tayrona. Los participantes deben traer al menos sus equipos ligeros de buceo, el resto de los equipos serán proporcionados por el INVEMAR.


La duración del trabajo de campo es de un día completo por lo que se recomienda traer protector solar, gorra y ropa seca de repuesto.

El día miércoles un grupo reducido de participantes volverá a la Bahía de Chegue a retirar los *squidpops* que fueron dejados el día anterior. 

## Trabajo laboratorio

EL procesamiento de las muestras de pastos marinos se realizará en el INVEMAR y el día lunes les serán presentadas las condiciones para trabajar en los laboratorios. 

## Reporte

Se espera que para el día viernes cada uno de los equipos elabore un informe de las actividades realizadas y realice una presentación sobre las conclusiones obtenidas. Uno de los productos finales será un conjunto de datos que será subido a OBIS y registrado en GBIF. Potencialmente se podrá esquematizar un posible *data paper* que describa los datos obtenidos de esta actividad.


